SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `nostradamus` DEFAULT CHARACTER SET latin1 ;
CREATE SCHEMA IF NOT EXISTS `information_schema` ;
USE `nostradamus` ;

-- -----------------------------------------------------
-- Table `nostradamus`.`dernier_stock`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `nostradamus`.`dernier_stock` (
  `id_produit` INT(11) NOT NULL ,
  `stock` INT(11) NULL DEFAULT NULL ,
  PRIMARY KEY (`id_produit`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nostradamus`.`produits`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `nostradamus`.`produits` (
  `id_produit` INT(11) NOT NULL AUTO_INCREMENT ,
  `nom_produit` VARCHAR(255) NULL DEFAULT NULL ,
  `code_produit` VARCHAR(255) NULL DEFAULT NULL ,
  `actif` VARCHAR(45) NOT NULL DEFAULT 'true' ,
  `visible` VARCHAR(45) NOT NULL DEFAULT 'true' ,
  PRIMARY KEY (`id_produit`) )
ENGINE = MyISAM
AUTO_INCREMENT = 860
DEFAULT CHARACTER SET = latin1
COMMENT = 'table des produits';


-- -----------------------------------------------------
-- Table `nostradamus`.`prop`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `nostradamus`.`prop` (
  `id_prop` INT(11) NOT NULL AUTO_INCREMENT ,
  `id_produit` VARCHAR(45) NULL DEFAULT NULL ,
  `id_propriete` INT(11) NULL DEFAULT NULL ,
  `valeur` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`id_prop`) ,
  INDEX `prop_index` (`id_propriete` ASC, `valeur` ASC) )
ENGINE = MyISAM
AUTO_INCREMENT = 859
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nostradamus`.`proprietes`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `nostradamus`.`proprietes` (
  `id_propriete` INT(11) NOT NULL AUTO_INCREMENT ,
  `nom_propriete` VARCHAR(45) NULL DEFAULT NULL ,
  `type_propriete` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`id_propriete`) )
ENGINE = MyISAM
AUTO_INCREMENT = 132
DEFAULT CHARACTER SET = latin1
COMMENT = 'table des propriétés des produits';


-- -----------------------------------------------------
-- Table `nostradamus`.`stocks`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `nostradamus`.`stocks` (
  `id_stock` INT(11) NOT NULL AUTO_INCREMENT ,
  `id_utilisateur` INT(11) NOT NULL DEFAULT '0' ,
  `date` DATETIME NULL DEFAULT NULL ,
  `etat_stock` INT(10) NULL DEFAULT '0' ,
  `id_produit` INT(10) NULL DEFAULT NULL ,
  PRIMARY KEY (`id_stock`) ,
  INDEX `index_stocks` (`date` ASC, `id_produit` ASC) )
ENGINE = MyISAM
AUTO_INCREMENT = 1408
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `nostradamus`.`valeur`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `nostradamus`.`valeur` (
  `id_valeur` INT(11) NOT NULL AUTO_INCREMENT ,
  `id_propriete` INT(11) NULL DEFAULT NULL ,
  `value` VARCHAR(1000) NULL DEFAULT NULL ,
  PRIMARY KEY (`id_valeur`) )
ENGINE = MyISAM
AUTO_INCREMENT = 370
DEFAULT CHARACTER SET = latin1;

USE `information_schema` ;

-- -----------------------------------------------------
-- Table `information_schema`.`CHARACTER_SETS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`CHARACTER_SETS` (
  `CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DEFAULT_COLLATE_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DESCRIPTION` VARCHAR(60) NOT NULL DEFAULT '' ,
  `MAXLEN` BIGINT(3) NOT NULL DEFAULT '0' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`COLLATIONS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`COLLATIONS` (
  `COLLATION_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `ID` BIGINT(11) NOT NULL DEFAULT '0' ,
  `IS_DEFAULT` VARCHAR(3) NOT NULL DEFAULT '' ,
  `IS_COMPILED` VARCHAR(3) NOT NULL DEFAULT '' ,
  `SORTLEN` BIGINT(3) NOT NULL DEFAULT '0' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`COLLATION_CHARACTER_SET_APPLICABILITY`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`COLLATION_CHARACTER_SET_APPLICABILITY` (
  `COLLATION_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`COLUMNS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`COLUMNS` (
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ORDINAL_POSITION` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `COLUMN_DEFAULT` LONGTEXT NULL DEFAULT NULL ,
  `IS_NULLABLE` VARCHAR(3) NOT NULL DEFAULT '' ,
  `DATA_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `CHARACTER_MAXIMUM_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CHARACTER_OCTET_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `NUMERIC_PRECISION` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `NUMERIC_SCALE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CHARACTER_SET_NAME` VARCHAR(32) NULL DEFAULT NULL ,
  `COLLATION_NAME` VARCHAR(32) NULL DEFAULT NULL ,
  `COLUMN_TYPE` LONGTEXT NOT NULL ,
  `COLUMN_KEY` VARCHAR(3) NOT NULL DEFAULT '' ,
  `EXTRA` VARCHAR(27) NOT NULL DEFAULT '' ,
  `PRIVILEGES` VARCHAR(80) NOT NULL DEFAULT '' ,
  `COLUMN_COMMENT` VARCHAR(255) NOT NULL DEFAULT '' )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`COLUMN_PRIVILEGES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`COLUMN_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '' ,
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`ENGINES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`ENGINES` (
  `ENGINE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `SUPPORT` VARCHAR(8) NOT NULL DEFAULT '' ,
  `COMMENT` VARCHAR(80) NOT NULL DEFAULT '' ,
  `TRANSACTIONS` VARCHAR(3) NULL DEFAULT NULL ,
  `XA` VARCHAR(3) NULL DEFAULT NULL ,
  `SAVEPOINTS` VARCHAR(3) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`EVENTS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`EVENTS` (
  `EVENT_CATALOG` VARCHAR(64) NULL DEFAULT NULL ,
  `EVENT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `EVENT_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '' ,
  `TIME_ZONE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `EVENT_BODY` VARCHAR(8) NOT NULL DEFAULT '' ,
  `EVENT_DEFINITION` LONGTEXT NOT NULL ,
  `EVENT_TYPE` VARCHAR(9) NOT NULL DEFAULT '' ,
  `EXECUTE_AT` DATETIME NULL DEFAULT NULL ,
  `INTERVAL_VALUE` VARCHAR(256) NULL DEFAULT NULL ,
  `INTERVAL_FIELD` VARCHAR(18) NULL DEFAULT NULL ,
  `SQL_MODE` VARCHAR(8192) NOT NULL DEFAULT '' ,
  `STARTS` DATETIME NULL DEFAULT NULL ,
  `ENDS` DATETIME NULL DEFAULT NULL ,
  `STATUS` VARCHAR(18) NOT NULL DEFAULT '' ,
  `ON_COMPLETION` VARCHAR(12) NOT NULL DEFAULT '' ,
  `CREATED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `LAST_ALTERED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `LAST_EXECUTED` DATETIME NULL DEFAULT NULL ,
  `EVENT_COMMENT` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ORIGINATOR` BIGINT(10) NOT NULL DEFAULT '0' ,
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '' ,
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DATABASE_COLLATION` VARCHAR(32) NOT NULL DEFAULT '' )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`FILES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`FILES` (
  `FILE_ID` BIGINT(4) NOT NULL DEFAULT '0' ,
  `FILE_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `FILE_TYPE` VARCHAR(20) NOT NULL DEFAULT '' ,
  `TABLESPACE_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `TABLE_CATALOG` VARCHAR(64) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NULL DEFAULT NULL ,
  `TABLE_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `LOGFILE_GROUP_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `LOGFILE_GROUP_NUMBER` BIGINT(4) NULL DEFAULT NULL ,
  `ENGINE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `FULLTEXT_KEYS` VARCHAR(64) NULL DEFAULT NULL ,
  `DELETED_ROWS` BIGINT(4) NULL DEFAULT NULL ,
  `UPDATE_COUNT` BIGINT(4) NULL DEFAULT NULL ,
  `FREE_EXTENTS` BIGINT(4) NULL DEFAULT NULL ,
  `TOTAL_EXTENTS` BIGINT(4) NULL DEFAULT NULL ,
  `EXTENT_SIZE` BIGINT(4) NOT NULL DEFAULT '0' ,
  `INITIAL_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `MAXIMUM_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `AUTOEXTEND_SIZE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CREATION_TIME` DATETIME NULL DEFAULT NULL ,
  `LAST_UPDATE_TIME` DATETIME NULL DEFAULT NULL ,
  `LAST_ACCESS_TIME` DATETIME NULL DEFAULT NULL ,
  `RECOVER_TIME` BIGINT(4) NULL DEFAULT NULL ,
  `TRANSACTION_COUNTER` BIGINT(4) NULL DEFAULT NULL ,
  `VERSION` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `ROW_FORMAT` VARCHAR(10) NULL DEFAULT NULL ,
  `TABLE_ROWS` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `AVG_ROW_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `MAX_DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `INDEX_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `DATA_FREE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CREATE_TIME` DATETIME NULL DEFAULT NULL ,
  `UPDATE_TIME` DATETIME NULL DEFAULT NULL ,
  `CHECK_TIME` DATETIME NULL DEFAULT NULL ,
  `CHECKSUM` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `STATUS` VARCHAR(20) NOT NULL DEFAULT '' ,
  `EXTRA` VARCHAR(255) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`GLOBAL_STATUS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`GLOBAL_STATUS` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`GLOBAL_VARIABLES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`GLOBAL_VARIABLES` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`KEY_COLUMN_USAGE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`KEY_COLUMN_USAGE` (
  `CONSTRAINT_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `CONSTRAINT_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ORDINAL_POSITION` BIGINT(10) NOT NULL DEFAULT '0' ,
  `POSITION_IN_UNIQUE_CONSTRAINT` BIGINT(10) NULL DEFAULT NULL ,
  `REFERENCED_TABLE_SCHEMA` VARCHAR(64) NULL DEFAULT NULL ,
  `REFERENCED_TABLE_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `REFERENCED_COLUMN_NAME` VARCHAR(64) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`PARTITIONS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`PARTITIONS` (
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `PARTITION_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `SUBPARTITION_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `PARTITION_ORDINAL_POSITION` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `SUBPARTITION_ORDINAL_POSITION` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `PARTITION_METHOD` VARCHAR(12) NULL DEFAULT NULL ,
  `SUBPARTITION_METHOD` VARCHAR(12) NULL DEFAULT NULL ,
  `PARTITION_EXPRESSION` LONGTEXT NULL DEFAULT NULL ,
  `SUBPARTITION_EXPRESSION` LONGTEXT NULL DEFAULT NULL ,
  `PARTITION_DESCRIPTION` LONGTEXT NULL DEFAULT NULL ,
  `TABLE_ROWS` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `AVG_ROW_LENGTH` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `DATA_LENGTH` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `MAX_DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `INDEX_LENGTH` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `DATA_FREE` BIGINT(21) UNSIGNED NOT NULL DEFAULT '0' ,
  `CREATE_TIME` DATETIME NULL DEFAULT NULL ,
  `UPDATE_TIME` DATETIME NULL DEFAULT NULL ,
  `CHECK_TIME` DATETIME NULL DEFAULT NULL ,
  `CHECKSUM` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `PARTITION_COMMENT` VARCHAR(80) NOT NULL DEFAULT '' ,
  `NODEGROUP` VARCHAR(12) NOT NULL DEFAULT '' ,
  `TABLESPACE_NAME` VARCHAR(64) NULL DEFAULT NULL )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`PLUGINS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`PLUGINS` (
  `PLUGIN_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `PLUGIN_VERSION` VARCHAR(20) NOT NULL DEFAULT '' ,
  `PLUGIN_STATUS` VARCHAR(10) NOT NULL DEFAULT '' ,
  `PLUGIN_TYPE` VARCHAR(80) NOT NULL DEFAULT '' ,
  `PLUGIN_TYPE_VERSION` VARCHAR(20) NOT NULL DEFAULT '' ,
  `PLUGIN_LIBRARY` VARCHAR(64) NULL DEFAULT NULL ,
  `PLUGIN_LIBRARY_VERSION` VARCHAR(20) NULL DEFAULT NULL ,
  `PLUGIN_AUTHOR` VARCHAR(64) NULL DEFAULT NULL ,
  `PLUGIN_DESCRIPTION` LONGTEXT NULL DEFAULT NULL ,
  `PLUGIN_LICENSE` VARCHAR(80) NULL DEFAULT NULL )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`PROCESSLIST`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`PROCESSLIST` (
  `ID` BIGINT(4) NOT NULL DEFAULT '0' ,
  `USER` VARCHAR(16) NOT NULL DEFAULT '' ,
  `HOST` VARCHAR(64) NOT NULL DEFAULT '' ,
  `DB` VARCHAR(64) NULL DEFAULT NULL ,
  `COMMAND` VARCHAR(16) NOT NULL DEFAULT '' ,
  `TIME` INT(7) NOT NULL DEFAULT '0' ,
  `STATE` VARCHAR(64) NULL DEFAULT NULL ,
  `INFO` LONGTEXT NULL DEFAULT NULL )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`PROFILING`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`PROFILING` (
  `QUERY_ID` INT(20) NOT NULL DEFAULT '0' ,
  `SEQ` INT(20) NOT NULL DEFAULT '0' ,
  `STATE` VARCHAR(30) NOT NULL DEFAULT '' ,
  `DURATION` DECIMAL(9,6) NOT NULL DEFAULT '0.000000' ,
  `CPU_USER` DECIMAL(9,6) NULL DEFAULT NULL ,
  `CPU_SYSTEM` DECIMAL(9,6) NULL DEFAULT NULL ,
  `CONTEXT_VOLUNTARY` INT(20) NULL DEFAULT NULL ,
  `CONTEXT_INVOLUNTARY` INT(20) NULL DEFAULT NULL ,
  `BLOCK_OPS_IN` INT(20) NULL DEFAULT NULL ,
  `BLOCK_OPS_OUT` INT(20) NULL DEFAULT NULL ,
  `MESSAGES_SENT` INT(20) NULL DEFAULT NULL ,
  `MESSAGES_RECEIVED` INT(20) NULL DEFAULT NULL ,
  `PAGE_FAULTS_MAJOR` INT(20) NULL DEFAULT NULL ,
  `PAGE_FAULTS_MINOR` INT(20) NULL DEFAULT NULL ,
  `SWAPS` INT(20) NULL DEFAULT NULL ,
  `SOURCE_FUNCTION` VARCHAR(30) NULL DEFAULT NULL ,
  `SOURCE_FILE` VARCHAR(20) NULL DEFAULT NULL ,
  `SOURCE_LINE` INT(20) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`REFERENTIAL_CONSTRAINTS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`REFERENTIAL_CONSTRAINTS` (
  `CONSTRAINT_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `CONSTRAINT_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `UNIQUE_CONSTRAINT_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `UNIQUE_CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `UNIQUE_CONSTRAINT_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `MATCH_OPTION` VARCHAR(64) NOT NULL DEFAULT '' ,
  `UPDATE_RULE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `DELETE_RULE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `REFERENCED_TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`ROUTINES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`ROUTINES` (
  `SPECIFIC_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ROUTINE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `ROUTINE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ROUTINE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ROUTINE_TYPE` VARCHAR(9) NOT NULL DEFAULT '' ,
  `DTD_IDENTIFIER` VARCHAR(64) NULL DEFAULT NULL ,
  `ROUTINE_BODY` VARCHAR(8) NOT NULL DEFAULT '' ,
  `ROUTINE_DEFINITION` LONGTEXT NULL DEFAULT NULL ,
  `EXTERNAL_NAME` VARCHAR(64) NULL DEFAULT NULL ,
  `EXTERNAL_LANGUAGE` VARCHAR(64) NULL DEFAULT NULL ,
  `PARAMETER_STYLE` VARCHAR(8) NOT NULL DEFAULT '' ,
  `IS_DETERMINISTIC` VARCHAR(3) NOT NULL DEFAULT '' ,
  `SQL_DATA_ACCESS` VARCHAR(64) NOT NULL DEFAULT '' ,
  `SQL_PATH` VARCHAR(64) NULL DEFAULT NULL ,
  `SECURITY_TYPE` VARCHAR(7) NOT NULL DEFAULT '' ,
  `CREATED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `LAST_ALTERED` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `SQL_MODE` VARCHAR(8192) NOT NULL DEFAULT '' ,
  `ROUTINE_COMMENT` VARCHAR(64) NOT NULL DEFAULT '' ,
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '' ,
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '' ,
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DATABASE_COLLATION` VARCHAR(32) NOT NULL DEFAULT '' )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`SCHEMATA`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`SCHEMATA` (
  `CATALOG_NAME` VARCHAR(512) NULL DEFAULT NULL ,
  `SCHEMA_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `DEFAULT_CHARACTER_SET_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DEFAULT_COLLATION_NAME` VARCHAR(32) NOT NULL DEFAULT '' ,
  `SQL_PATH` VARCHAR(512) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`SCHEMA_PRIVILEGES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`SCHEMA_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '' ,
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`SESSION_STATUS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`SESSION_STATUS` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`SESSION_VARIABLES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`SESSION_VARIABLES` (
  `VARIABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `VARIABLE_VALUE` VARCHAR(1024) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`STATISTICS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`STATISTICS` (
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `NON_UNIQUE` BIGINT(1) NOT NULL DEFAULT '0' ,
  `INDEX_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `INDEX_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `SEQ_IN_INDEX` BIGINT(2) NOT NULL DEFAULT '0' ,
  `COLUMN_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `COLLATION` VARCHAR(1) NULL DEFAULT NULL ,
  `CARDINALITY` BIGINT(21) NULL DEFAULT NULL ,
  `SUB_PART` BIGINT(3) NULL DEFAULT NULL ,
  `PACKED` VARCHAR(10) NULL DEFAULT NULL ,
  `NULLABLE` VARCHAR(3) NOT NULL DEFAULT '' ,
  `INDEX_TYPE` VARCHAR(16) NOT NULL DEFAULT '' ,
  `COMMENT` VARCHAR(16) NULL DEFAULT NULL )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`TABLES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`TABLES` (
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ENGINE` VARCHAR(64) NULL DEFAULT NULL ,
  `VERSION` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `ROW_FORMAT` VARCHAR(10) NULL DEFAULT NULL ,
  `TABLE_ROWS` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `AVG_ROW_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `MAX_DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `INDEX_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `DATA_FREE` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `AUTO_INCREMENT` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CREATE_TIME` DATETIME NULL DEFAULT NULL ,
  `UPDATE_TIME` DATETIME NULL DEFAULT NULL ,
  `CHECK_TIME` DATETIME NULL DEFAULT NULL ,
  `TABLE_COLLATION` VARCHAR(32) NULL DEFAULT NULL ,
  `CHECKSUM` BIGINT(21) UNSIGNED NULL DEFAULT NULL ,
  `CREATE_OPTIONS` VARCHAR(255) NULL DEFAULT NULL ,
  `TABLE_COMMENT` VARCHAR(80) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`TABLE_CONSTRAINTS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`TABLE_CONSTRAINTS` (
  `CONSTRAINT_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `CONSTRAINT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `CONSTRAINT_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `CONSTRAINT_TYPE` VARCHAR(64) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`TABLE_PRIVILEGES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`TABLE_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '' ,
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`TRIGGERS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`TRIGGERS` (
  `TRIGGER_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TRIGGER_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TRIGGER_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `EVENT_MANIPULATION` VARCHAR(6) NOT NULL DEFAULT '' ,
  `EVENT_OBJECT_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `EVENT_OBJECT_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `EVENT_OBJECT_TABLE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `ACTION_ORDER` BIGINT(4) NOT NULL DEFAULT '0' ,
  `ACTION_CONDITION` LONGTEXT NULL DEFAULT NULL ,
  `ACTION_STATEMENT` LONGTEXT NOT NULL ,
  `ACTION_ORIENTATION` VARCHAR(9) NOT NULL DEFAULT '' ,
  `ACTION_TIMING` VARCHAR(6) NOT NULL DEFAULT '' ,
  `ACTION_REFERENCE_OLD_TABLE` VARCHAR(64) NULL DEFAULT NULL ,
  `ACTION_REFERENCE_NEW_TABLE` VARCHAR(64) NULL DEFAULT NULL ,
  `ACTION_REFERENCE_OLD_ROW` VARCHAR(3) NOT NULL DEFAULT '' ,
  `ACTION_REFERENCE_NEW_ROW` VARCHAR(3) NOT NULL DEFAULT '' ,
  `CREATED` DATETIME NULL DEFAULT NULL ,
  `SQL_MODE` VARCHAR(8192) NOT NULL DEFAULT '' ,
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '' ,
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '' ,
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '' ,
  `DATABASE_COLLATION` VARCHAR(32) NOT NULL DEFAULT '' )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`USER_PRIVILEGES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`USER_PRIVILEGES` (
  `GRANTEE` VARCHAR(81) NOT NULL DEFAULT '' ,
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `PRIVILEGE_TYPE` VARCHAR(64) NOT NULL DEFAULT '' ,
  `IS_GRANTABLE` VARCHAR(3) NOT NULL DEFAULT '' )
ENGINE = MEMORY
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `information_schema`.`VIEWS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `information_schema`.`VIEWS` (
  `TABLE_CATALOG` VARCHAR(512) NULL DEFAULT NULL ,
  `TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '' ,
  `TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '' ,
  `VIEW_DEFINITION` LONGTEXT NOT NULL ,
  `CHECK_OPTION` VARCHAR(8) NOT NULL DEFAULT '' ,
  `IS_UPDATABLE` VARCHAR(3) NOT NULL DEFAULT '' ,
  `DEFINER` VARCHAR(77) NOT NULL DEFAULT '' ,
  `SECURITY_TYPE` VARCHAR(7) NOT NULL DEFAULT '' ,
  `CHARACTER_SET_CLIENT` VARCHAR(32) NOT NULL DEFAULT '' ,
  `COLLATION_CONNECTION` VARCHAR(32) NOT NULL DEFAULT '' )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
